MESES = {
    'ene': 'Enero',
    'feb': 'Febrero',
    'mar': 'Marzo',
    'abr': 'Abril',
    'may': 'Mayo',
    'jun': 'Junio',
    'jul': 'Julio',
    'ago': 'Agosto',
    'sep': 'Septiembre',
    'oct': 'Octubre',
    'nov': 'Noviembre',
    'dic': 'Diciembre',
}

SEXOS = {
    'Mas': 'Masculino',
    'Fem': 'Femenino',
}

TABLA = {
    18: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Mas','jun':'Mas','jul':'Mas','ago':'Mas','sep':'Mas','oct':'Mas','nov':'Mas','dic':'Mas'},
    19: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Fem','jun':'Mas','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Mas','nov':'Fem','dic':'Fem'},
    20: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Mas','jun':'Mas','jul':'Mas','ago':'Mas','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Mas'},
    21: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Fem','jun':'Fem','jul':'Fem','ago':'Fem','sep':'Fem','oct':'Fem','nov':'Fem','dic':'Fem'},
    22: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Mas','jun':'Fem','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Fem','nov':'Fem','dic':'Fem'},
    23: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Mas','nov':'Mas','dic':'Mas'},
    24: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Fem','nov':'Fem','dic':'Fem'},
    25: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Mas','nov':'Mas','dic':'Mas'},
    26: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Fem','oct':'Fem','nov':'Fem','dic':'Fem'},
    27: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Mas','oct':'Mas','nov':'Mas','dic':'Mas'},
    28: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Fem','dic':'Fem'},
    29: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Mas','dic':'Mas'},
    30: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    31: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    32: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    33: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    34: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    35: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    36: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    37: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    38: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    39: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    40: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    41: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    42: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    43: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
    44: {'ene':'Mas','feb':'Fem','mar':'Mas','abr':'Fem','may':'Mas','jun':'Fem','jul':'Mas','ago':'Fem','sep':'Mas','oct':'Fem','nov':'Mas','dic':'Fem'},
    45: {'ene':'Fem','feb':'Mas','mar':'Fem','abr':'Mas','may':'Fem','jun':'Mas','jul':'Fem','ago':'Mas','sep':'Fem','oct':'Mas','nov':'Fem','dic':'Mas'},
}
